# Generated by Django 6.0.4 on 2026-07-12 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appointment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followupreminder',
            name='notification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_reminder', to='core.notification'),
        ),
        migrations.AlterField(
            model_name='followupreminder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending delivery'), ('Sent', 'Sent'), ('Failed', 'Delivery failed'), ('Completed', 'Follow-up completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'status'], name='appointment_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='followupreminder',
            index=models.Index(fields=['status', 'reminder_date'], name='reminder_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['patient', 'is_read', 'created_at'], name='notification_patient_read_idx'),
        ),
        migrations.AddIndex(
            model_name='smscampaign',
            index=models.Index(fields=['status', 'scheduled_date'], name='campaign_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('queue_number__gt', 0)), name='appointment_positive_queue'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Pending', 'Approved', 'Scheduled', 'Rescheduled', 'Completed', 'Cancelled', 'No-show'])), name='appointment_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['Low', 'Medium', 'High'])), name='appointment_valid_priority'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('consultation_type__in', ['Online', 'In-person'])), name='appointment_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('appointment_date', 'queue_number'), name='appointment_unique_daily_queue'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('patient', 'appointment_date', 'appointment_time'), name='appointment_unique_patient_slot'),
        ),
        migrations.AddConstraint(
            model_name='followupreminder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Pending', 'Sent', 'Failed', 'Completed', 'Cancelled'])), name='reminder_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='followupreminder',
            constraint=models.UniqueConstraint(condition=models.Q(('consultation__isnull', False)), fields=('consultation',), name='reminder_unique_consultation'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['Medicine', 'Supplies', 'Equipment'])), name='inventory_valid_category'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('name', 'unit'), name='inventory_unique_name_unit'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ['SMS', 'System'])), name='notification_valid_channel'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Pending', 'Sent', 'Failed'])), name='notification_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('sex__in', ['M', 'F', 'O'])), name='patient_valid_sex'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Active', 'Inactive'])), name='patient_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('philhealth_number', ''), _negated=True), fields=('philhealth_number',), name='patient_unique_philhealth'),
        ),
        migrations.AddConstraint(
            model_name='smscampaign',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Draft', 'Scheduled', 'Sent', 'Failed'])), name='campaign_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='smscampaign',
            constraint=models.CheckConstraint(condition=models.Q(('sent_count__lte', models.F('recipient_count'))), name='campaign_sent_within_recipient_count'),
        ),
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['Physician', 'Nurse', 'Midwife', 'Admin', 'BHW'])), name='staff_valid_role'),
        ),
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Active', 'Inactive'])), name='staff_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id', ''), _negated=True), fields=('employee_id',), name='staff_unique_employee_id'),
        ),
        migrations.AddConstraint(
            model_name='triagecase',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['Low', 'Medium', 'High'])), name='triage_valid_priority'),
        ),
        migrations.AddConstraint(
            model_name='triagecase',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 100)), name='triage_confidence_range'),
        ),
    ]
