# Generated by Django 6.0.4 on 2026-07-12 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_normalize_workflow_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='consultationrecord',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_record', to='core.appointment'),
        ),
        migrations.AlterField(
            model_name='followupreminder',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='core.consultationrecord'),
        ),
        migrations.AlterField(
            model_name='followupreminder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_reminders', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='triagecase',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triage_cases', to='core.patient'),
        ),
    ]
