from django.contrib import admin
from django.urls import include, path
from core import web_views

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("api/", include("core.urls")),
    path("", web_views.dashboard, name="dashboard"),
    path("admin-dashboard/", web_views.admin_dashboard, name="admin_dashboard"),
    path("specialist-dashboard/", web_views.specialist_dashboard, name="specialist_dashboard"),
    path("patient-dashboard/", web_views.patient_dashboard, name="patient_dashboard"),
    path("login/", web_views.login_view, name="login"),
    path("register/", web_views.register_view, name="register"),
    path("logout/", web_views.logout_view, name="logout"),
    path("patient-portal/", web_views.patient_portal, name="patient_portal"),
    path("patient-portal/<str:tab>/", web_views.patient_portal, name="patient_portal_tab"),
    path("patient-portal/profile/submit/", web_views.update_profile, name="update_profile"),
    path("patient-portal/appointments/schedule/", web_views.schedule_appointment, name="schedule_appointment"),
    path("patient-portal/appointments/<int:pk>/cancel/", web_views.cancel_appointment, name="cancel_appointment"),
    path("patient-portal/assessment/submit/", web_views.submit_assessment, name="submit_assessment"),
    path("patient-portal/notifications/<int:pk>/read/", web_views.read_notification, name="read_notification"),
    path("users/", web_views.user_list, name="users"),
    path("users/new/", web_views.user_edit, name="user_create"),
    path("users/<int:pk>/edit/", web_views.user_edit, name="user_edit"),
    path("patients/", web_views.patient_list, name="patients"),
    path("patients/new/", web_views.patient_edit, name="patient_create"),
    path("patients/<int:pk>/", web_views.patient_detail, name="patient_detail"),
    path("patients/<int:pk>/edit/", web_views.patient_edit, name="patient_edit"),
    path("patients/<int:pk>/archive/", web_views.patient_archive, name="patient_archive"),
    path("patients/<int:pk>/reactivate/", web_views.patient_reactivate, name="patient_reactivate"),
    path("appointments/", web_views.appointment_list, name="appointments"),
    path("appointments/new/", web_views.appointment_edit, name="appointment_create"),
    path("appointments/<int:pk>/edit/", web_views.appointment_edit, name="appointment_edit"),
    path("appointments/<int:pk>/confirm/", web_views.appointment_confirm, name="appointment_confirm"),
    path("specialist/appointments/<int:pk>/acknowledge/", web_views.specialist_acknowledge, name="specialist_acknowledge"),
    path("specialist/notifications/<int:pk>/read/", web_views.read_staff_notification, name="read_staff_notification"),
    path("teleconsultation/", web_views.teleconsultation, name="teleconsultation"),
    path("ehr/", web_views.records, name="records"),
    path("ehr/new/", web_views.consultation_edit, name="consultation_create"),
    path("ehr/<int:pk>/edit/", web_views.consultation_edit, name="consultation_edit"),
    path("triage/", web_views.triage_list, name="triage"),
    path("communications/", web_views.communications, name="communications"),
    path("communications/new/", web_views.campaign_edit, name="campaign_create"),
    path("communications/<int:pk>/edit/", web_views.campaign_edit, name="campaign_edit"),
    path("reports/", web_views.reports, name="reports"),
    path("admin/", web_views.administration, name="administration"),
    path("admin/inventory/new/", web_views.inventory_edit, name="inventory_create"),
    path("admin/inventory/<int:pk>/edit/", web_views.inventory_edit, name="inventory_edit"),
]
